[package]
name = "deploy"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
contracts = { path = "../..", package = "contracts" }
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.36.0" }
starknet = ">=2.9.2"


[dev-dependencies]
cairo_test = "2.9.2"

[[target.starknet-contract]]
build-external-contracts = [
    "contracts::*"
]
