version: "3.9"

services:
  app:
    image: private-erc20-api:latest
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - PATH=/root/.nargo/bin:$PATH
    command: /bin/sh -c "yarn install && yarn dev || tail -f /dev/null"

