direction_selector = ["", "", "", ""]
in_amount = ""
in_commitment_nullifier = ""
in_commitment_nullifier_hash = ""
in_commitment_secret = ""
new_direction_selector = ["", "", "", ""]
new_path = ["", "", "", ""]
new_root = ""
out_amount_receiver = ""
out_amount_sender = ""
out_commitments = ["", ""]
path = ["", "", "", ""]
receiver_account = ""
root = ""
