in_amount = ""
in_bliding = ""
in_commitment_nullifier_hash = ""
in_direction_selector = ["", ""]
in_path = ["", ""]
in_private_key = ""
in_root = ""
out_receiver_account = ""
out_receiver_amount = ""
out_receiver_bliding = ""
out_receiver_commitment = ""
out_root = ""
out_sender_amount = ""
out_sender_bliding = ""
out_sender_commitment = ""
out_subtree_root_direction = [""]
out_subtree_root_path = [""]
