[package]
name = "contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
# garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.15.3" }
starknet = "2.9.2"

[cairo]
sierra-replace-ids = false

[dev-dependencies]
snforge_std = "0.33.0"
cairo_test = "2.9.2"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true