amount = ""
balance = ""
commitment = ""
direction_selector = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nullifier = ""
nullifier_hash = ""
path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
root = ""
secret = ""
